### ISSUE TITLE
Unable to boot Ubuntu on Zynq Z7030

### ISSUE THREAD

**Issue by pedrombmachado** [SundanceMultiprocessorTechnology/VCS-1_FM191_FW#5]
@Pranjali-Shinde reported:
I am using vivado version 2017.1 and petalinux 2017.4. Have followed the procedure though the Zynq does not boot! Can you please share the petalinux project inorder to know the problem?

Thank you,

**Comment by pedrombmachado** [comment]
@Pranjali-Shinde,
   The first step to do is use the same version of Vivado i.e. 2017.4. You should always to use the same version as the Xilinx tool will be pointing to specific folders which do not match. Please Install Vivado 2017.4 and then try to build following the steps. Please report back if the problem got solved.
Bw
Pedro

**Comment by pedrombmachado** [comment]
@Pranjali-Shinde wrote:
"These are the links followed:

* [link1](https://medium.com/developments-and-implementations-on-zynq-7000-ap/install-ubuntu-16-04-lts-on-zynq-zc702-using-petalinux-2016-4-e1da902eaff7)

* [link2](https://medium.com/developments-and-implementations-on-zynq-7000-ap/interfacing-a-usb-webcam-and-enable-usb-tethering-on-zynq-7000-ap-soc-running-linux-1ba6d836749d.)
I am not understanding where am I going wrong, in spite of executing all the commands without error."

**Comment by pedrombmachado** [comment]
Hi @Pranjali-Shinde,
   Several steps should be followed to mitigate such problems.
1. Have you checked if the board boots with the image that is shared [here](https://tinyurl.com/emc2-fm191-ros-img-gz)?
a) If not, check the power.
b) Check the LED's sequence to see if they go off.
2. Have you formatted the card to FAT32 before burning the new image?
a) if not format the card to FAT32
3) Are all the required files in the boot partition? Compare with the image of point 1.
a) If not then you must have them.
4) Is the uSD card at least class 10x?
a) If not, replace the card
b) I would suggest that you use only SanDisk cards as some other cards might not work. 
5. Have you completed the Xilinx training that I sent you?
a. If not, I suggest you stop everything that you are doing and finish the Xilinx training first.

**Comment by Pranjali-Shinde** [comment]
Hi @pedrombmachado,
The following steps have been followed.
1. Yes, it boots. The red LED blinks at the start and then goes OFF. 
2. Yes, I have formatted the SD card and made two partitions.
     a). FAT32-BOOT
     b). ext4-rootfs
3. Yes, I have made a comparison of the files required for the booting and they are there.
4. I am using SanDisk class 10
5. I am going through it as I have not finished yet. Yes, I will finish it first.

**Comment by PedroSundance** [comment]
What is the output of the booting procedure via UART? In other words why does it stop?

________________________________

**Comment by Pranjali-Shinde** [comment]
There is no output via UART. Whereas the LEDs on the board goes off and nothing emerges on the serial terminal.

**Comment by PedroSundance** [comment]
Have you tested with our image?
________________________________

**Comment by Pranjali-Shinde** [comment]
Yes, I did test with your image. It works. Whereas, I have generated the Petalinux kernel with USB drivers and it does not!

**Comment by PedroSundance** [comment]
Have you compared the file names in our image with yours in the boot partition? Do you have the same number of files and names? If not replace only the ones that you generated a leave the other files there.
________________________________

**Comment by Pranjali-Shinde** [comment]
Yes, I did the comparison. There are more files in mine. Whereas other files are same as yours.
Okay.

**Comment by pedrombmachado** [comment]
@Pranjali-Shinde  are you using the correct board files from Trenz? 
@timoteogb [instructions](https://github.com/SundanceMultiprocessorTechnology/VCS-1_FM191_FW/wiki) work fine for generating a bootable image. There are only 2 issues because he reported that Eth and the USB are not working. I guess it happens because the respective kernel modules are not on.  Therefore, can you please follow the steps and check if the Eth and USB support modules are selected.
You can find extra information here:
* [link0](http://www.wiki.xilinx.com/petalinux+getting+started)
* [link1](https://www.xilinx.com/support/documentation/sw_manuals/petalinux2013_10/ug980-petalinux-board-bringup.pdf)
* [link2](http://www.xilinx.com/support/documentation/sw_manuals/petalinux2013_10/ug980-petalinux-board-bringup.pdf)

**Comment by Pranjali-Shinde** [comment]
I replaced the files same as yours and left the additional files which I generated as it is,  and the system boots. The system is logged in through the arm login and the password. I am not understanding why with my files it does not work.

**Comment by pedrombmachado** [comment]
Hi @Pranjali-Shinde ,
Those are great news. Probably because you missed something when you were doing the steps. You will find the answer for sure if do the Xilinx training. Please let me know if the USB and Eth are now working. BTW the Zed Camera also works using USB2, therefore, you should be able to start using it if the USB is well configured. @EmilieWheatley  and @timoteogb  are currently working on the USB3.
Bw.
Pedro

**Comment by Pranjali-Shinde** [comment]
Okay. As of my knowledge I have not missed anything instead have done it properly. Okay. I will find out what I have missed. Just to cross check and to know if I am on the right track, the training you mentioned, is the SD card which you gave me, right? Because I am going through it. Or is it some other training?
Timoteo had told that USB2.0 is powered by making the jumper connection JP5, which I have done already. I am figuring out the USB because the board is unable to identify the USB cam connected to it.

**Comment by PedroSundance** [comment]
Hi Pranjali,
   Yes the Xilinx training is in the uSD card that Shipped to you. Look inside the presentations folder and start in the Vivado Design 0 folder.
Bw
Pedro
________________________________

**Comment by pedrombmachado** [comment]
@Pranjali-Shinde ,
 There is a difference between detecting a device and recognise it as a camera.
check if an usb device is present using:
```
$ lsusb
```
check if the drivers are assigned correctly
```
$ sudo lshw
```
check if there are kernel errors/warnings
```
$ dmesg | tail
```
you might find useful the following [link](ftp://ftp.wayne.edu/ldp/en/Webcam-HOWTO/Webcam-HOWTO-single.html)

**Comment by Pranjali-Shinde** [comment]
Hi @PedroSundance Thank you so much. However, I tried with all the commands and there are no errors neither warnings.It does not still identify the USB2.0
I am checking the links and the guide.

**Comment by pedrombmachado** [comment]
Hi @Pranjali-Shinde ,
  There is an [issue](https://github.com/SundanceMultiprocessorTechnology/VCS-1_FM191_FW/issues/4) open about that subject and you may want to contribute to solving it. The Unable to boot Ubuntu on Zynq Z7030 issue is now solved and closed.
